
language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules
    - sysconfcpus

env:
  - ELM_VERSION=elm0.19.0

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - node -v
  - npm --version
  - npm install -g elm@$ELM_VERSION
  - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-original
  # Make sure that the wrapper script exits with the return-code of "elm-original"
  - printf "#\041/bin/bash\necho \"Running elm with sysconfcpus -n 2\"\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-original \"\$@\"\nexit \$?\n" > $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm

jdk:
  - openjdk8
  - openjdk11

script:
  - ./gradlew assemble
  - ./gradlew check -i
